###
GET http://localhost:3001

###
GET http://localhost:3001/users?sortDesc=false

###
POST http://localhost:3001/users
Authorization: abcd
Content-Type: application/json

{
  "username": "amy",
  "email": "amy@example.com"
}

###
DELETE http://localhost:3001/users/2

###
GET http://localhost:3001/users/1

###
GET http://localhost:3001/users/aaaa

###
GET http://localhost:3001/users/posts